import type { AssetRole, Protocol, SecurityZone } from './types'

export const PROTOCOL_HELP: Record<Protocol, string> = {
  TCP: 'A reliable way for two computers to hold a conversation. It checks that data arrives and resends missing pieces.',
  UDP: 'A faster send-and-forget method. It does not confirm delivery, so it is common for discovery, streaming, and time-sensitive device traffic.',
  ICMP: 'Network status and error messages. Ping uses ICMP to check whether a host can be reached.',
  DNS: 'The network phone book. It turns names such as server.example into IP addresses.',
  HTTP: 'Ordinary web traffic used by browsers, APIs, and many device web pages. By itself, it is not encrypted.',
  TLS: 'Encryption that protects traffic in transit. HTTPS is web traffic protected by TLS.',
  SSH: 'An encrypted way to remotely administer a computer or network device from a command line.',
  MODBUS: 'A simple industrial protocol used to read and change numbered values in PLCs, meters, and controllers.',
  DNP3: 'A control and monitoring protocol used mainly by electric and water utilities to communicate with remote equipment.',
  'ETHERNET/IP': 'An industrial automation protocol that carries CIP messages over Ethernet. Despite the name, it does not mean ordinary Internet traffic.',
  BACNET: 'A building-automation protocol used by HVAC, lighting, fire, and access-control systems.',
  'OPC UA': 'A vendor-neutral way for industrial software and equipment to share structured data securely.',
  S7COMM: 'A Siemens protocol used to program, monitor, and exchange data with S7 PLCs.',
  PROFINET: 'A real-time industrial Ethernet protocol used by controllers, remote I/O, drives, and other factory equipment.',
  'IEC 104': 'A utility SCADA protocol used to send telemetry and control messages between control centers and substations. It is different from IEC 62443.',
  FINS: 'An Omron protocol used to read, write, and control PLC data over a network.',
  'HART-IP': 'A protocol that carries data from industrial instruments, such as pressure or temperature transmitters, over IP networks.',
  MMS: 'A standard messaging service used by industrial systems; it is especially common for IEC 61850 substation devices.',
  GOOSE: 'Very fast IEC 61850 event messages used between substation devices, often for protection trips. They usually stay on the local Ethernet network.',
  ETHERCAT: 'A high-speed industrial Ethernet system used for tightly timed machine control, motion, drives, and remote I/O.',
  OTHER: 'Traffic NetMap could not confidently place into one of its named protocol categories.',
}

export const ASSET_ROLE_HELP: Record<AssetRole, string> = {
  PLC: 'Programmable Logic Controller: a rugged computer that runs the logic controlling a machine or process.',
  HMI: 'Human-Machine Interface: the screen operators use to view alarms, measurements, and controls.',
  RTU: 'Remote Terminal Unit: equipment at a remote site that gathers measurements and carries out control commands.',
  Historian: 'A server that stores time-based process data so people can review trends and past events.',
  'Engineering Workstation': 'A computer used to configure, program, and troubleshoot industrial controllers.',
  'OPC Gateway': 'A bridge that collects or translates industrial data so different systems can share it.',
  'Building Controller': 'A controller that runs building systems such as HVAC, lighting, or access control.',
  'Safety System': 'A separate control system designed to move a process to a safe state when dangerous conditions occur.',
  'Field Device': 'A sensor, meter, relay, drive, valve, or actuator that directly measures or affects the physical process.',
  Server: 'A computer that provides data or services to other systems.',
  Workstation: 'A general-purpose computer used by a person.',
  'Network Infrastructure': 'A switch, router, firewall, wireless controller, or similar device that moves or protects network traffic.',
  'External Endpoint': 'A host outside the private network, usually on another organization\'s network or the public Internet.',
  Unknown: 'NetMap does not have enough evidence to make a useful role guess.',
}

export const ZONE_HELP: Record<SecurityZone, string> = {
  Enterprise: 'Office IT systems such as business workstations, email, and corporate applications.',
  DMZ: 'A buffer area between networks. Systems here can exchange approved data without giving either side direct access to the other.',
  Operations: 'Plant-support services such as historians, application servers, and industrial data gateways.',
  Supervisory: 'Systems people use to watch and manage the process, such as HMIs and engineering workstations.',
  Control: 'Controllers that make automatic process decisions, such as PLCs and building controllers.',
  Safety: 'Safety-instrumented systems that should be strongly separated because they protect people, equipment, or the environment.',
  Field: 'Devices closest to the physical process, such as sensors, meters, relays, remote units, and actuators.',
  External: 'A device outside the private environment or organization.',
  Unassigned: 'No zone has been chosen and NetMap could not make a confident suggestion.',
}

export const CONTROL_HELP = {
  interface: 'The network adapter NetMap listens to, such as Ethernet or Wi-Fi. Only traffic visible to that adapter can be captured.',
  bpf: 'BPF means Berkeley Packet Filter. It limits what is recorded before capture, for example “host 10.0.0.1” or “port 502”.',
  search: 'Show IP addresses, hostnames, MAC addresses, hardware vendors, or IPv4 CIDR ranges that match. Separate several searches with commas, spaces, or semicolons.',
  time: 'Keep only conversations observed inside this date-and-time range.',
  port: 'A port is a numbered service door on a host. For example, Modbus/TCP commonly uses port 502.',
  protocol: 'A protocol is the agreed set of rules two systems use to communicate. Select several to show traffic matching any selected protocol.',
  otProtocol: 'OT means Operational Technology: computers that monitor or control physical equipment. ICS means Industrial Control System.',
  minBytes: 'Hide conversations that transferred fewer total bytes than this number.',
  minPackets: 'Hide conversations containing fewer packets than this number. A packet is one small piece of network data.',
  hostScope: 'Internal means a private/local IP used inside a network. External means a public IP outside that private address space.',
  boundary: 'Choose whether a conversation must touch an internal host, touch an external host, or cross between the two.',
  connections: 'Choose one combined line per pair of hosts, every separate port/flow, or no lines. Combined lines are easier and faster on large maps.',
  spacing: 'Controls how much room the automatic layout puts between hosts. You can still drag any host afterward.',
  neighborhood: 'A hop is one network conversation away. Depth 1 adds direct peers; depth 2 also adds the peers of those peers.',
  cap: 'A safety limit on how many host-pair lines or individual flows NetMap draws. Lower values keep very large captures responsive.',
  edgeLabels: 'Writes protocol, port, and traffic information on connection lines. Labels can make a busy map harder to read.',
  subnet: 'A subnet is a group of nearby IP addresses. NetMap groups IPv4 hosts by their first three numbers, such as 192.168.1.x.',
  isolates: 'An isolated host has no visible connection after the current filters are applied.',
  noise: 'Hides very small conversations so larger communication patterns stand out. Small traffic is not necessarily unimportant or harmless.',
  pathDirection: 'Controls which arrows become bright when you hover a host. Outbound means sent from it; inbound means sent to it.',
  iec62443: 'IEC is the International Electrotechnical Commission. IEC 62443 is a family of cybersecurity standards for industrial systems.',
  zone: 'A zone is a logical group of assets that need similar cybersecurity protection—like putting equipment with the same security needs in one room.',
  conduit: 'A conduit is the controlled communication path between zones—like a guarded doorway that permits approved traffic between rooms.',
  anomalies: 'Compares later traffic with an early learning period and marks new pairs, protocols, ports, or large volume changes. A flag is a clue, not proof of an attack.',
  baseline: 'The early percentage of the capture treated as “normal” for comparison. It is only as trustworthy as the traffic recorded during that period.',
  timeline: 'Replays connections in the order NetMap first observed them. It does not replay every packet or the exact duration of each conversation.',
  savedViews: 'Stores the current filters and layout so you can return to the same map view later.',
  layout: 'Force directed keeps connected hosts near each other; hierarchical arranges levels; circle and grid use simple fixed shapes.',
  links: 'Shows or hides connection lines without removing the hosts.',
  names: 'Shows hostnames learned passively from captured DNS when available; otherwise the IP address remains visible.',
  fit: 'Centers and scales all currently visible hosts so they fit in the map area.',
  resetLayout: 'Runs the selected automatic layout again. It can replace positions you created by dragging hosts.',
  png: 'Saves a picture of the current map.',
  csv: 'Saves the currently visible flow records as a spreadsheet-friendly text file.',
  assetRole: 'The job a device appears to perform. Auto-detection is a best-effort guess from names and traffic; you can correct it manually.',
  merge: 'Off by default: a successful import replaces the current map. Turn it on only when the new capture belongs in the same combined investigation.',
} as const
